

#include "Corner.hpp"
#include "Edge.hpp"
#include "Hexagon.hpp"
#include "ResourceType.hpp"





Hexagon TERRAIN[] = 
{
	Hexagon(1, WHEAT),
	Hexagon(2, WHEAT),
	Hexagon(3, WHEAT),
	Hexagon(4, WHEAT),
	Hexagon(5, WOOD),
	Hexagon(6, WOOD),
	Hexagon(7, WOOD),
	Hexagon(8, WOOD),
	Hexagon(9, SHEEP),
	Hexagon(10, SHEEP),
	Hexagon(11, SHEEP),
	Hexagon(12, SHEEP),
	Hexagon(13, STONE),
	Hexagon(14, STONE),
	Hexagon(15, STONE),
	Hexagon(16, BRICK),
	Hexagon(17, BRICK),
	Hexagon(18, BRICK),
	Hexagon(19, DESERT)
};


Corner CORNERS[] =
{
	Corner(1),
	Corner(2),
	Corner(3),
	Corner(4),
	Corner(5),
	Corner(6),
	Corner(7),
	Corner(8),
	Corner(9),
	Corner(10),
	Corner(11),
	Corner(12),
	Corner(13),
	Corner(14),
	Corner(15),
	Corner(16),
	Corner(17),
	Corner(18),
	Corner(19),
	Corner(20),
	Corner(21),
	Corner(22),
	Corner(23),
	Corner(24),
	Corner(25),
	Corner(26),
	Corner(27),
	Corner(28),
	Corner(29),
	Corner(30),
	Corner(31),
	Corner(32),
	Corner(33),
	Corner(34),
	Corner(35),
	Corner(36),
	Corner(37),
	Corner(38),
	Corner(39),
	Corner(40),
	Corner(41),
	Corner(42),
	Corner(43),
	Corner(44),
	Corner(45),
	Corner(46),
	Corner(47),
	Corner(48),
	Corner(49),
	Corner(50),
	Corner(51),
	Corner(52),
	Corner(53),
	Corner(54)
};


Edge EDGES[] =
{
		Edge(1),
	Edge(2),
	Edge(3),
	Edge(4),
	Edge(5),
	Edge(6),
	Edge(7),
	Edge(8),
	Edge(9),
	Edge(10),
	Edge(11),
	Edge(12),
	Edge(13),
	Edge(14),
	Edge(15),
	Edge(16),
	Edge(17),
	Edge(18),
	Edge(19),
	Edge(20),
	Edge(21),
	Edge(22),
	Edge(23),
	Edge(24),
	Edge(25),
	Edge(26),
	Edge(27),
	Edge(28),
	Edge(29),
	Edge(30),
	Edge(31),
	Edge(32),
	Edge(33),
	Edge(34),
	Edge(35),
	Edge(36),
	Edge(37),
	Edge(38),
	Edge(39),
	Edge(40),
	Edge(41),
	Edge(42),
	Edge(43),
	Edge(44),
	Edge(45),
	Edge(46),
	Edge(47),
	Edge(48),
	Edge(49),
	Edge(50),
	Edge(51),
	Edge(52),
	Edge(53),
	Edge(54),
	Edge(55),
	Edge(56),
	Edge(57),
	Edge(58),
	Edge(59),
	Edge(60),
	Edge(61),
	Edge(62),
	Edge(63),
	Edge(64),
	Edge(65),
	Edge(66),
	Edge(67),
	Edge(68),
	Edge(69),
	Edge(70),
	Edge(71),
	Edge(72)
};


uint8_t HEXAGON_CORNERS[][3] =  // {HexagonID, EdgeID}
{
	{1, 1, Hexagon::Corners::BOTTOM_LEFT},
	{1, 2, Hexagon::Corners::BOTTOM_RIGHT},
	{1, 5, Hexagon::Corners::RIGHT},
	{1, 10, Hexagon::Corners::TOP_RIGHT},
	{1, 9, Hexagon::Corners::TOP_LEFT},
	{1, 4, Hexagon::Corners::LEFT},
	
	{2, 3, Hexagon::Corners::BOTTOM_LEFT},
	{2, 4, Hexagon::Corners::BOTTOM_RIGHT},
	{2, 9, Hexagon::Corners::RIGHT},
	{2, 15, Hexagon::Corners::TOP_RIGHT},
	{2, 14, Hexagon::Corners::TOP_LEFT},
	{2, 8, Hexagon::Corners::LEFT},
	
	{3, 5, Hexagon::Corners::BOTTOM_LEFT},
	{3, 6, Hexagon::Corners::BOTTOM_RIGHT},
	{3, 11, Hexagon::Corners::RIGHT},
	{3, 17, Hexagon::Corners::TOP_RIGHT},
	{3, 16, Hexagon::Corners::TOP_LEFT},
	{3, 10, Hexagon::Corners::LEFT},
	
	{4, 7, Hexagon::Corners::BOTTOM_LEFT},
	{4, 8, Hexagon::Corners::BOTTOM_RIGHT},
	{4, 14, Hexagon::Corners::RIGHT},
	{4, 20, Hexagon::Corners::TOP_RIGHT},
	{4, 19, Hexagon::Corners::TOP_LEFT},
	{4, 13, Hexagon::Corners::LEFT},
	
	{5, 9, Hexagon::Corners::BOTTOM_LEFT},
	{5, 10, Hexagon::Corners::BOTTOM_RIGHT},
	{5, 16, Hexagon::Corners::RIGHT},
	{5, 22, Hexagon::Corners::TOP_RIGHT},
	{5, 21, Hexagon::Corners::TOP_LEFT},
	{5, 15, Hexagon::Corners::LEFT},
	
	{6, 11, Hexagon::Corners::BOTTOM_LEFT},
	{6, 12, Hexagon::Corners::BOTTOM_RIGHT},
	{6, 18, Hexagon::Corners::RIGHT},
	{6, 24, Hexagon::Corners::TOP_RIGHT},
	{6, 23, Hexagon::Corners::TOP_LEFT},
	{6, 17, Hexagon::Corners::LEFT},
	
	{7, 14, Hexagon::Corners::BOTTOM_LEFT},
	{7, 15, Hexagon::Corners::BOTTOM_RIGHT},
	{7, 21, Hexagon::Corners::RIGHT},
	{7, 27, Hexagon::Corners::TOP_RIGHT},
	{7, 26, Hexagon::Corners::TOP_LEFT},
	{7, 20, Hexagon::Corners::LEFT},
	
	{8, 16, Hexagon::Corners::BOTTOM_LEFT},
	{8, 17, Hexagon::Corners::BOTTOM_RIGHT},
	{8, 23, Hexagon::Corners::RIGHT},
	{8, 29, Hexagon::Corners::TOP_RIGHT},
	{8, 28, Hexagon::Corners::TOP_LEFT},
	{8, 22, Hexagon::Corners::LEFT},
	
	{9, 19, Hexagon::Corners::BOTTOM_LEFT},
	{9, 20, Hexagon::Corners::BOTTOM_RIGHT},
	{9, 26, Hexagon::Corners::RIGHT},
	{9, 32, Hexagon::Corners::TOP_RIGHT},
	{9, 31, Hexagon::Corners::TOP_LEFT},
	{9, 25, Hexagon::Corners::LEFT},
	
	{10, 21, Hexagon::Corners::BOTTOM_LEFT},
	{10, 22, Hexagon::Corners::BOTTOM_RIGHT},
	{10, 28, Hexagon::Corners::RIGHT},
	{10, 34, Hexagon::Corners::TOP_RIGHT},
	{10, 33, Hexagon::Corners::TOP_LEFT},
	{10, 27, Hexagon::Corners::LEFT},
	
	{11, 23, Hexagon::Corners::BOTTOM_LEFT},
	{11, 24, Hexagon::Corners::BOTTOM_RIGHT},
	{11, 30, Hexagon::Corners::RIGHT},
	{11, 36, Hexagon::Corners::TOP_RIGHT},
	{11, 35, Hexagon::Corners::TOP_LEFT},
	{11, 29, Hexagon::Corners::LEFT},
	
	{12, 26, Hexagon::Corners::BOTTOM_LEFT},
	{12, 27, Hexagon::Corners::BOTTOM_RIGHT},
	{12, 33, Hexagon::Corners::RIGHT},
	{12, 39, Hexagon::Corners::TOP_RIGHT},
	{12, 38, Hexagon::Corners::TOP_LEFT},
	{12, 32, Hexagon::Corners::LEFT},
	
	{13, 28, Hexagon::Corners::BOTTOM_LEFT},
	{13, 29, Hexagon::Corners::BOTTOM_RIGHT},
	{13, 35, Hexagon::Corners::RIGHT},
	{13, 41, Hexagon::Corners::TOP_RIGHT},
	{13, 40, Hexagon::Corners::TOP_LEFT},
	{13, 34, Hexagon::Corners::LEFT},
	
	{14, 31, Hexagon::Corners::BOTTOM_LEFT},
	{14, 32, Hexagon::Corners::BOTTOM_RIGHT},
	{14, 38, Hexagon::Corners::RIGHT},
	{14, 44, Hexagon::Corners::TOP_RIGHT},
	{14, 43, Hexagon::Corners::TOP_LEFT},
	{14, 37, Hexagon::Corners::LEFT},
	
	{15, 33, Hexagon::Corners::BOTTOM_LEFT},
	{15, 34, Hexagon::Corners::BOTTOM_RIGHT},
	{15, 40, Hexagon::Corners::RIGHT},
	{15, 46, Hexagon::Corners::TOP_RIGHT},
	{15, 45, Hexagon::Corners::TOP_LEFT},
	{15, 39, Hexagon::Corners::LEFT},
	
	{16, 35, Hexagon::Corners::BOTTOM_LEFT},
	{16, 36, Hexagon::Corners::BOTTOM_RIGHT},
	{16, 42, Hexagon::Corners::RIGHT},
	{16, 48, Hexagon::Corners::TOP_RIGHT},
	{16, 47, Hexagon::Corners::TOP_LEFT},
	{16, 41, Hexagon::Corners::LEFT},
	
	{17, 38, Hexagon::Corners::BOTTOM_LEFT},
	{17, 39, Hexagon::Corners::BOTTOM_RIGHT},
	{17, 45, Hexagon::Corners::RIGHT},
	{17, 50, Hexagon::Corners::TOP_RIGHT},
	{17, 49, Hexagon::Corners::TOP_LEFT},
	{17, 44, Hexagon::Corners::LEFT},
	
	{18, 40, Hexagon::Corners::BOTTOM_LEFT},
	{18, 41, Hexagon::Corners::BOTTOM_RIGHT},
	{18, 47, Hexagon::Corners::RIGHT},
	{18, 52, Hexagon::Corners::TOP_RIGHT},
	{18, 51, Hexagon::Corners::TOP_LEFT},
	{18, 46, Hexagon::Corners::LEFT},
	
	{19, 45, Hexagon::Corners::BOTTOM_LEFT},
	{19, 46, Hexagon::Corners::BOTTOM_RIGHT},
	{19, 51, Hexagon::Corners::RIGHT},
	{19, 54, Hexagon::Corners::TOP_RIGHT},
	{19, 53, Hexagon::Corners::TOP_LEFT},
	{19, 50, Hexagon::Corners::LEFT}
};


uint8_t HEXAGON_EDGES[][2] =  // {HexagonID, EdgeID}
{
	{1, 1, Hexagon::Edges::BOTTOM},
	{1, 3, Hexagon::Edges::BOTTOM_RIGHT},
	{1, 8, Hexagon::Edges::TOP_RIGHT},
	{1, 11, Hexagon::Edges::TOP},
	{1, 7, Hexagon::Edges::TOP_LEFT},
	{1, 2, Hexagon::Edges::BOTTOM_LEFT},

	{2, 4, Hexagon::Edges::BOTTOM},
	{2, 7, Hexagon::Edges::BOTTOM_RIGHT},
	{2, 15, Hexagon::Edges::TOP_RIGHT},
	{2, 19, Hexagon::Edges::TOP},
	{2, 14, Hexagon::Edges::TOP_LEFT},
	{2, 6, Hexagon::Edges::BOTTOM_LEFT},

	{3, 5, Hexagon::Edges::BOTTOM},
	{3, 9, Hexagon::Edges::BOTTOM_RIGHT},
	{3, 17, Hexagon::Edges::TOP_RIGHT},
	{3, 20, Hexagon::Edges::TOP},
	{3, 16, Hexagon::Edges::TOP_LEFT},
	{3, 8, Hexagon::Edges::BOTTOM_LEFT},

	{4, 10, Hexagon::Edges::BOTTOM},
	{4, 14, Hexagon::Edges::BOTTOM_RIGHT},
	{4, 22, Hexagon::Edges::TOP_RIGHT},
	{4, 27, Hexagon::Edges::TOP},
	{4, 21, Hexagon::Edges::TOP_LEFT},
	{4, 13, Hexagon::Edges::BOTTOM_LEFT},

	{5, 11, Hexagon::Edges::BOTTOM},
	{5, 16, Hexagon::Edges::BOTTOM_RIGHT},
	{5, 24, Hexagon::Edges::TOP_RIGHT},
	{5, 28, Hexagon::Edges::TOP},
	{5, 23, Hexagon::Edges::TOP_LEFT},
	{5, 15, Hexagon::Edges::BOTTOM_LEFT},

	{6, 12, Hexagon::Edges::BOTTOM},
	{6, 18, Hexagon::Edges::BOTTOM_RIGHT},
	{6, 26, Hexagon::Edges::TOP_RIGHT},
	{6, 29, Hexagon::Edges::TOP},
	{6, 25, Hexagon::Edges::TOP_LEFT},
	{6, 17, Hexagon::Edges::BOTTOM_LEFT},

	{7, 19, Hexagon::Edges::BOTTOM},
	{7, 23, Hexagon::Edges::BOTTOM_RIGHT},
	{7, 32, Hexagon::Edges::TOP_RIGHT},
	{7, 36, Hexagon::Edges::TOP},
	{7, 31, Hexagon::Edges::TOP_LEFT},
	{7, 22, Hexagon::Edges::BOTTOM_LEFT},

	{8, 20, Hexagon::Edges::BOTTOM},
	{8, 25, Hexagon::Edges::BOTTOM_RIGHT},
	{8, 34, Hexagon::Edges::TOP_RIGHT},
	{8, 37, Hexagon::Edges::TOP},
	{8, 33, Hexagon::Edges::TOP_LEFT},
	{8, 24, Hexagon::Edges::BOTTOM_LEFT},

	{9, 27, Hexagon::Edges::BOTTOM},
	{9, 31, Hexagon::Edges::BOTTOM_RIGHT},
	{9, 39, Hexagon::Edges::TOP_RIGHT},
	{9, 44, Hexagon::Edges::TOP},
	{9, 38, Hexagon::Edges::TOP_LEFT},
	{9, 30, Hexagon::Edges::BOTTOM_LEFT},

	{10, 28, Hexagon::Edges::BOTTOM},
	{10, 33, Hexagon::Edges::BOTTOM_RIGHT},
	{10, 41, Hexagon::Edges::TOP_RIGHT},
	{10, 45, Hexagon::Edges::TOP},
	{10, 40, Hexagon::Edges::TOP_LEFT},
	{10, 32, Hexagon::Edges::BOTTOM_LEFT},

	{11, 29, Hexagon::Edges::BOTTOM},
	{11, 35, Hexagon::Edges::BOTTOM_RIGHT},
	{11, 43, Hexagon::Edges::TOP_RIGHT},
	{11, 46, Hexagon::Edges::TOP},
	{11, 42, Hexagon::Edges::TOP_LEFT},
	{11, 34, Hexagon::Edges::BOTTOM_LEFT},

	{12, 36, Hexagon::Edges::BOTTOM},
	{12, 40, Hexagon::Edges::BOTTOM_RIGHT},
	{12, 49, Hexagon::Edges::TOP_RIGHT},
	{12, 53, Hexagon::Edges::TOP},
	{12, 48, Hexagon::Edges::TOP_LEFT},
	{12, 39, Hexagon::Edges::BOTTOM_LEFT},

	{13, 37, Hexagon::Edges::BOTTOM},
	{13, 42, Hexagon::Edges::BOTTOM_RIGHT},
	{13, 51, Hexagon::Edges::TOP_RIGHT},
	{13, 54, Hexagon::Edges::TOP},
	{13, 50, Hexagon::Edges::TOP_LEFT},
	{13, 41, Hexagon::Edges::BOTTOM_LEFT},

	{14, 44, Hexagon::Edges::BOTTOM},
	{14, 48, Hexagon::Edges::BOTTOM_RIGHT},
	{14, 56, Hexagon::Edges::TOP_RIGHT},
	{14, 61, Hexagon::Edges::TOP},
	{14, 55, Hexagon::Edges::TOP_LEFT},
	{14, 47, Hexagon::Edges::BOTTOM_LEFT},

	{15, 45, Hexagon::Edges::BOTTOM},
	{15, 50, Hexagon::Edges::BOTTOM_RIGHT},
	{15, 58, Hexagon::Edges::TOP_RIGHT},
	{15, 62, Hexagon::Edges::TOP},
	{15, 57, Hexagon::Edges::TOP_LEFT},
	{15, 49, Hexagon::Edges::BOTTOM_LEFT},

	{16, 46, Hexagon::Edges::BOTTOM},
	{16, 52, Hexagon::Edges::BOTTOM_RIGHT},
	{16, 60, Hexagon::Edges::TOP_RIGHT},
	{16, 63, Hexagon::Edges::TOP},
	{16, 59, Hexagon::Edges::TOP_LEFT},
	{16, 51, Hexagon::Edges::BOTTOM_LEFT},

	{17, 53, Hexagon::Edges::BOTTOM},
	{17, 57, Hexagon::Edges::BOTTOM_RIGHT},
	{17, 65, Hexagon::Edges::TOP_RIGHT},
	{17, 68, Hexagon::Edges::TOP},
	{17, 64, Hexagon::Edges::TOP_LEFT},
	{17, 56, Hexagon::Edges::BOTTOM_LEFT},

	{18, 54, Hexagon::Edges::BOTTOM},
	{18, 59, Hexagon::Edges::BOTTOM_RIGHT},
	{18, 67, Hexagon::Edges::TOP_RIGHT},
	{18, 69, Hexagon::Edges::TOP},
	{18, 66, Hexagon::Edges::TOP_LEFT},
	{18, 58, Hexagon::Edges::BOTTOM_LEFT},

	{19, 62, Hexagon::Edges::BOTTOM},
	{19, 66, Hexagon::Edges::BOTTOM_RIGHT},
	{19, 71, Hexagon::Edges::TOP_RIGHT},
	{19, 72, Hexagon::Edges::TOP},
	{19, 70, Hexagon::Edges::TOP_LEFT},
	{19, 65, Hexagon::Edges::BOTTOM_LEFT}
};
